In [2]:
import numpy as np
import pandas as pd
import yfinance as yf

df = yf.download('^N225')
df.to_csv('N225.csv')
df.head()

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1965-01-05,1257.719971,1257.719971,1257.719971,1257.719971,1257.719971,0
1965-01-06,1263.989990,1263.989990,1263.989990,1263.989990,1263.989990,0
1965-01-07,1274.270020,1274.270020,1274.270020,1274.270020,1274.270020,0
1965-01-08,1286.430054,1286.430054,1286.430054,1286.430054,1286.430054,0
1965-01-12,1288.540039,1288.540039,1288.540039,1288.540039,1288.540039,0

In [5]:
import torch
import torch.nn as nn

class CNN1d(nn.Module):
    def __init__(
            self, 
            seq_len, 
            input_channels, 
            n_features, 
            n_filters,
            droprate: float = 0.1,
        ):
        super().__init__()
        conv_output_size = 10 # calc
        self.l1 = nn.Covn1d(input_channels, n_filters[0], kernel_size=n_features[0])
        self.a1 = nn.ReLU()
        self.l2 = nn.MaxPool1d(kernel_size=2)
        self.l3 = nn.Conv1d(n_features[2], n_features[3], kernel_size=2)
        self.a3 = nn.ReLU()
        self.l4 = nn.Flatten()
        self.l5 = nn.Dropout(droprate)
        self.l6 = nn.Dense(conv_output_size, 1)
        self.layers = [
            self.l1, self.a1,
            self.l2, 
            self.l3, self.a3,
            self.l4,
            self.l5,
            self.l6
        ]
        
    def forward(self, x: torch.Tensor):
        for layer in self.layers:
            x = layer(x)
        
        return x

In [ ]:

class Trainer:
    
    def __init__(self, model, optimizer, epochs=100):
        self.model = model
        self.optimizer = optimizer
        self.epochs = epochs
    
    def fit(self, train_dataset, val_dataset):
        history = {'train_loss': [], 'valid_loss': []}
        for epoch in range(self.epochs):
            train_loss = .0
            for X, y in train_dataset:
                loss = self.train_step(X, y)
                train_loss += loss.item()

            train_loss /= len(train_dataset)
            print('epoch: {}, train loss: {}'.format(epoch, train_loss))
            history['train_loss'].append(train_loss)
        
        self.history = history
        return
    
    def predict(self, test_dataset):
        pass
    
    def _compute_loss(self, y, yhat):
        return self.criterion(yhat, y)
    
    def _train_step(self, x, y):
        self.model.train()
        yhat = self.model(x)
        loss = self._compute_loss(y, yhat)
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()
        return yhat, loss
    
    def _eval_step(self, x, y):
        self.model.eval()
        yhat = self.model(x)
        loss = self._compute_loss(y, yhat)
        return yhat, loss